import React from "react";
class HomePage extends React.Component{
    constructor(props){
        super(props);
    }
    render(){
        return(
            <>
                <h2>Recommended</h2>
                <a href="/#/video/1">Click here for Test Video</a>
                <br />
                <h2>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut ullamcorper augue. Nulla convallis hendrerit aliquet. Integer tempus justo nec velit cursus molestie. Vivamus eu sagittis dolor. Vestibulum lacinia tortor quis nibh tincidunt viverra. Ut non consectetur mi. Duis congue maximus est, vel consectetur urna interdum quis. Praesent ac elit pulvinar, aliquam tortor et, interdum purus. Etiam id pretium ipsum. Nullam et suscipit libero. Donec commodo urna sit amet efficitur tincidunt. Quisque in magna imperdiet, convallis eros nec, sagittis sapien. Nam ac lectus sollicitudin, sollicitudin orci ac, aliquam nisl.

Quisque condimentum, velit et rhoncus molestie, quam nunc placerat libero, eu ultrices neque erat vitae felis. Proin maximus nec ante vitae dictum. Morbi hendrerit dignissim sem, a lobortis dolor fermentum sed. Phasellus faucibus quis odio non tempor. Vivamus nisi ante, ornare vel dignissim et, viverra scelerisque magna. Morbi molestie justo dui, id ullamcorper arcu mollis eget. Vivamus eget mi fermentum turpis tempus fermentum eget id lectus. Sed et elementum arcu. Nam tincidunt leo in elit efficitur consectetur. Nulla facilisi. Mauris accumsan, massa at eleifend consectetur, ex tellus congue libero, ac consequat dui felis at sapien. Aenean sit amet orci ut enim egestas auctor eget sit amet ligula. Vivamus egestas, arcu ut pretium pharetra, elit augue facilisis nunc, eget blandit nisi ligula non neque. Morbi ornare eros ac lectus pellentesque mattis. Sed at gravida augue. Morbi dictum feugiat massa, sit amet sagittis quam laoreet et.

Nullam tempus convallis lacus, a rutrum neque gravida eget. Integer id faucibus dui, vitae placerat arcu. Fusce id volutpat ligula. Nullam augue velit, fringilla at cursus nec, accumsan eget nulla. Donec eget ex semper, pharetra lacus eget, ultrices quam. Vestibulum posuere venenatis tincidunt. Cras a finibus dolor. Phasellus eu tellus auctor, porttitor massa non, bibendum felis. Vivamus sagittis vitae mi fermentum feugiat. Curabitur nec mi vulputate, pellentesque nulla eleifend, ornare felis. Sed sed leo augue. Donec pellentesque erat a ex egestas malesuada.

Curabitur finibus odio vitae tristique lacinia. Mauris a mi elementum lorem blandit commodo blandit eget sapien. Ut et bibendum nisi, id euismod lorem. In mollis egestas erat eget aliquet. Aenean tincidunt nunc quis est posuere scelerisque. Morbi mauris mi, blandit nec dictum ut, posuere in turpis. Phasellus egestas, orci ut placerat iaculis, enim neque mattis dolor, ac molestie magna felis in magna. Etiam interdum tellus ut vulputate malesuada. Integer vitae ullamcorper neque, vel viverra augue. Nullam sed malesuada dolor. Proin a augue sit amet enim aliquet sodales. Maecenas non pharetra lectus, eget vulputate erat. Vivamus interdum justo nec arcu faucibus rutrum. Aenean dignissim cursus vehicula.

Vestibulum vel turpis congue, lobortis augue tempus, pulvinar ipsum. Nam varius nunc eu eros viverra, sit amet luctus nibh cursus. Nam sed molestie dui. Donec efficitur nec turpis ac lacinia. Integer urna orci, varius eu turpis fringilla, ultricies laoreet eros. Ut vel velit aliquet, accumsan ligula tristique, euismod ligula. Aenean suscipit elit sit amet feugiat varius. Nam id tellus risus. Aliquam erat volutpat.

Aliquam lacinia nec ante aliquam auctor. Mauris maximus pellentesque sem. Pellentesque semper nulla sed facilisis consequat. Etiam laoreet aliquam massa, non blandit ante molestie vel. Suspendisse ac dignissim nisl. Phasellus eu sagittis tortor, eget scelerisque augue. Curabitur convallis justo sed hendrerit pretium. Pellentesque ultrices fermentum sodales. Suspendisse libero tellus, condimentum pretium tellus sed, laoreet rutrum nibh. Donec ornare lorem vitae finibus facilisis.

Sed luctus ultricies lorem, eu rutrum libero facilisis vel. Cras a velit ullamcorper, imperdiet orci non, fringilla risus. Nunc scelerisque, diam non commodo tincidunt, metus nisi mollis mauris, eu finibus tortor erat sed tellus. Aliquam tincidunt diam et ipsum sollicitudin, sed placerat orci eleifend. Sed eu lobortis eros, nec pellentesque est. Duis egestas lectus ac mi tincidunt tempus et ac purus. Cras faucibus sollicitudin ligula vel lacinia. Maecenas dui ligula, dignissim at justo sed, ullamcorper eleifend ipsum. Nulla gravida consectetur ante, in ullamcorper nisl pharetra non. Mauris eget feugiat justo, non suscipit elit. Duis consectetur iaculis odio, eu suscipit dolor tristique at. Proin vulputate lobortis odio et congue. Vivamus venenatis elit id commodo eleifend. Sed facilisis aliquet felis eget finibus.

In luctus eget neque eget mollis. Proin vulputate, lectus eu dapibus faucibus, diam justo ultrices est, vel maximus est augue in neque. Integer non imperdiet nulla. Fusce at posuere purus, eu consequat nulla. Cras consectetur ultrices leo, placerat aliquet dolor dictum sed. Donec lobortis venenatis elit, eu vestibulum diam laoreet sed. Sed molestie, tortor at accumsan semper, purus felis vulputate elit, vitae tristique justo lorem in risus. Phasellus tempor erat lectus, a sagittis eros lacinia id. Morbi molestie ultrices iaculis. Maecenas sed nibh ante.

Ut congue lectus a libero egestas eleifend. Ut tincidunt, tortor at sagittis efficitur, erat odio ultrices purus, vel porttitor nisl diam et dui. Aliquam ultrices gravida ultrices. Nam finibus euismod mi at consequat. Sed laoreet magna eget neque fringilla, et feugiat sem convallis. Sed sit amet metus fringilla risus maximus accumsan. Integer convallis vitae mi vel iaculis. Proin eu elementum enim. Maecenas pellentesque lacus quam, a venenatis tortor tincidunt et. Ut id venenatis diam. Nunc consequat bibendum augue. Proin blandit dignissim odio sed placerat. Nullam egestas velit eget ligula rutrum, non interdum mauris consectetur.

Maecenas rhoncus egestas urna sed tristique. Aenean mollis commodo nisi nec congue. Cras ligula leo, accumsan ac ante suscipit, tristique facilisis tellus. Vestibulum vitae rhoncus sem, sed lobortis nulla. In velit tortor, mattis sit amet purus vulputate, luctus cursus mi. Mauris nulla sapien, aliquet et luctus ac, convallis at odio. In in interdum sem. Donec libero diam, aliquet eu ex in, hendrerit accumsan nisi. Sed vitae tristique justo, sed mattis turpis. Phasellus porttitor elit urna, a pretium augue dictum non. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean vestibulum neque ac metus consectetur feugiat. Vestibulum iaculis aliquam dolor nec pretium. Nunc dapibus vulputate ultrices. Nunc at est leo. Nulla facilisi.

Donec malesuada placerat ornare. Suspendisse et mauris sit amet odio lacinia aliquet eget sit amet lectus. Nullam nec lorem tincidunt, eleifend odio at, finibus nisi. Donec convallis elementum scelerisque. Nunc at tincidunt metus, ornare tincidunt nisi. In hendrerit ornare erat, quis tincidunt nibh fringilla sit amet. Aliquam vitae ante purus. Pellentesque eu gravida urna, a facilisis dolor. Proin non tempor mi. Cras nec vulputate tellus, vitae euismod neque. Suspendisse rutrum fringilla nulla, vel fringilla augue fermentum a. Maecenas vehicula lacus ornare libero euismod elementum. Nunc pretium lacinia rhoncus. Aenean convallis consectetur libero, ut ultrices leo ornare et. Sed in scelerisque libero. Quisque vitae erat eget tellus faucibus dignissim.

Vestibulum vel arcu ut massa laoreet rhoncus. Duis sit amet sapien turpis. Fusce porta erat sed posuere porta. Praesent placerat, urna eget laoreet pellentesque, diam dui malesuada enim, quis pellentesque felis magna vitae diam. Maecenas ultricies tellus mauris, vitae elementum erat iaculis id. Duis tristique eleifend libero, eu cursus ligula lacinia ut. Donec fringilla mi non lectus consectetur malesuada. Aenean pellentesque auctor enim, ac eleifend sapien semper eget. Maecenas venenatis a metus at rutrum. Nam eu neque a massa imperdiet vestibulum a ut est. Phasellus tincidunt, nulla in lacinia commodo, enim metus pretium arcu, in ornare nulla diam et ante.

Pellentesque aliquet, turpis non egestas placerat, nisl eros euismod nisl, in blandit leo magna eu odio. Mauris a tortor tincidunt, molestie lacus et, fringilla erat. Suspendisse bibendum quis nunc ut sodales. Nunc ornare aliquam neque quis ultrices. Vestibulum mollis ullamcorper urna lacinia tempus. Fusce sollicitudin sem sed leo euismod, at tempus arcu mattis. Nulla sed porta risus. Aenean ultricies consequat ultrices. Praesent feugiat nisi quis laoreet faucibus. Maecenas luctus quam tortor, eu fermentum arcu dictum mattis. Nullam ac leo risus. Fusce auctor pretium est, quis ornare enim congue id. Praesent dictum, dui a semper iaculis, elit sem consequat massa, sed mollis orci nulla quis leo. Fusce et elit turpis.

Proin accumsan vulputate justo id interdum. Nulla facilisi. In imperdiet orci in elementum tempus. Aenean fringilla pellentesque posuere. Suspendisse nec nulla massa. Morbi non gravida odio. Curabitur vehicula ultrices nulla eget consectetur. Nunc at dui id mi scelerisque luctus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam ut orci eu mauris accumsan condimentum ac in dui. Etiam lorem odio, lobortis vitae orci elementum, molestie faucibus tellus. Suspendisse in quam dolor.

Maecenas sed vestibulum tortor. Aenean hendrerit rhoncus dictum. Cras at molestie mi. Vivamus diam nunc, venenatis ut cursus id, tincidunt quis elit. Fusce sollicitudin varius velit, sit amet imperdiet eros tincidunt eu. Aliquam eget efficitur mi, vitae lobortis metus. In ornare est elit, nec consequat ipsum lobortis vel.

Nunc convallis bibendum risus, sed pretium felis egestas eu. Duis egestas tincidunt ligula nec bibendum. Donec non dolor sapien. Vivamus lorem metus, pulvinar sit amet pulvinar et, pellentesque eget ex. Etiam aliquet tortor nec erat mattis posuere. Sed porta bibendum venenatis. Integer commodo egestas sollicitudin. Fusce dapibus elit id vehicula gravida. Cras lacinia mi at tortor sodales semper. Sed in sapien erat. Aenean sit amet aliquet nunc. Pellentesque eu dolor eget justo vehicula efficitur.

Nulla arcu ante, imperdiet quis facilisis eu, maximus eu metus. Donec vulputate felis sit amet nisl aliquet, quis lobortis velit elementum. Vivamus placerat egestas cursus. Phasellus aliquam leo vel velit consequat, sed dignissim nisl porttitor. Etiam non efficitur ex, a blandit ipsum. Pellentesque et lacus ante. Integer suscipit interdum scelerisque. Integer orci dolor, bibendum at congue vitae, blandit at quam. Aenean fringilla mauris et turpis dapibus aliquam. Nulla nisl massa, viverra id nisi at, feugiat cursus massa.

In iaculis vel lectus in fermentum. Ut in sapien non leo porta malesuada. Suspendisse tempor velit velit, quis ultricies mauris varius ut. Vestibulum ac sodales diam. Vivamus congue sed tortor et dictum. Aliquam erat volutpat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus varius neque vitae posuere dictum.

Sed commodo vel urna at imperdiet. Ut nec nisi ipsum. Sed vitae lacus sit amet purus sagittis pharetra sit amet eget magna. Integer id libero facilisis, volutpat arcu in, cursus diam. Nunc scelerisque ornare ex vitae condimentum. Cras dapibus consequat tellus, non vulputate ex dictum et. Aliquam eu auctor nisl, ac efficitur elit. Aliquam dapibus, ipsum fermentum maximus consequat, leo quam mollis leo, vitae iaculis nunc sem ac turpis. Quisque nulla felis, lobortis nec mattis et, hendrerit et purus. Vestibulum in pretium elit.

Aliquam et est urna. Integer ut vehicula leo. Duis dignissim porta lacus, vel rutrum metus sodales eu. Aliquam erat volutpat. Mauris posuere nulla nec lacus dignissim, nec dictum dolor tempus. Morbi ullamcorper, arcu cursus hendrerit convallis, justo est cursus orci, sit amet sagittis ipsum erat vel eros. Nullam at purus nec nisl sagittis tristique id quis augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis ac sodales enim. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Interdum et malesuada fames ac ante ipsum primis in faucibus.</h2>
            </>
        );
    }
}

export default HomePage;